### ISSUE TITLE
Can I use only google credentials? (and not include aws)

### ISSUE THREAD

**Issue by dariushazimi** [aniekanoffiong/speech-to-text#8]
Hi @aniekanoffiong 
Can I only use google credentials and NOT aws? I have added my google credentials to the service-account-file.json but when I run 'node server"  i get the error.

Can I just use the google api?

```
➜  speech-to-text git:(master) ✗ node server
module.js:549
    throw err;
    ^

Error: Cannot find module '../../config/aws-credentials'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/dariush/project/google/speech-to-text/libs/amazon/aws-s3-store.js:3:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by aniekanoffiong** [comment]
Alright. I will make some adjustments to allow for your use-case

**Comment by dariushazimi** [comment]
Thanks @aniekanoffiong

**Comment by pratheeshraniprakash** [comment]
Looking forward for the google-only version. 

I have made some customisations to the original code, such that only the Google speech-to-text API is used. But it does not display results for audio files longer than 3 minutes, even though the terminal says that the speech-to-text conversion has been completed.

**Comment by aniekanoffiong** [comment]
@pratheeshraniprakash at the time I worked on it, I noticed that the Google Speech To Text API only worked for ~1 minutes audio files
